### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xushaoyi** [jenniferlu717/Bracken#108]
Dear author, thanks for your kindly help! here is a problem when using bracken. the input is as follows:
"bracken -d /public/home/luhuijie/lib/kraken2 -i temp/kraken2/A1_report -t 24 -r 150  -o temp/bracken/A1.out"
but it went wrong and the detail report is as follows:
Traceback (most recent call last):
  File "/public/home/luhuijie/lib/miniconda2/envs/py27/bin/est_abundance.py", line 488, in <module>
    main()
  File "/public/home/luhuijie/lib/miniconda2/envs/py27/bin/est_abundance.py", line 222, in main
    report_vals = process_kraken_report(line)
  File "/public/home/luhuijie/lib/miniconda2/envs/py27/bin/est_abundance.py", line 140, in process_kraken_report
    level_reads = int(split_str[2])
IndexError: list index out of range

**Comment by jenniferlu717** [comment]
What does A1_report look like? Are you using the direct kraken output or are you using the output from the file generated by the --report flag?

**Comment by xushaoyi** [comment]
> What does A1_report look like? Are you using the direct kraken output or are you using the output from the file generated by the --report flag?

yes, I use the kraken output but it only generated a two column file, so maybe this is why the error happened

**Comment by jenniferlu717** [comment]
Yeah, Kraken's output shouldn't be only two columns. What was your kraken command line?

**Comment by jenniferlu717** [comment]
Something to note, Bracken does not work with the report generated by --use-mpa-style
