### ISSUE TITLE
Segmentation fault and Missing separate debuginfos

### ISSUE THREAD

**Issue by Zhenghong-Wang** [jenniferlu717/Bracken#125]
### error
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000407260 in ?? **()**
Missing separate debuginfos, use: debuginfo-install coreutils-8.22-18.el7.x86_64
(gdb) bt
#0  0x0000000000407260 in ?? ()
#1  0x0000000000407d2a in ?? ()
#2  0x00000000fffffff8 in ?? ()
#3  0x00002b940640ea58 in ?? ()
#4  0x000000000060c8c8 in ?? ()
#5  0x000000000060c8c0 in ?? ()
#6  0x0000000000000074 in ?? ()
#7  0x00002b9400000000 in ?? ()
#8  0x00002b948801ba90 in ?? ()
#9  0x00002b948801b910 in ?? ()
#10 0x00002b948801b8e0 in ?? ()
#11 0x0000000000000003 in ?? ()
#12 0x0000000000000028 in ?? ()
#13 0x0000000000000000 in ?? ()
##job report 
/opt/gridengine/default/spool/rock01/job_scripts/1570663: line 14: 455520 Segmentation fault      (core dumped) /lustre/home/wangzhenghong/miniconda2/Bracken-master/src/kmer2read_distr --seqid2taxid ${db}/kraken2/seqid2taxid.map --taxonomy ${db}/kraken2/taxonomy --kraken database.kraken --output database150mers.kraken -k 35 -l 150 -t 56   #line14
##
Dear Jenniferlu, I got the fault with Segmentation fault and missing separate debuginfos, I don't know what's wrong with it because just follow whole code on the github, can you give some suggestions or any guidence, thank you.
zai

**Comment by ulin27** [comment]
Hey Zai,

Did you end up figuring this out? I'm experiencing the same problem with the "kmer2read_distr --seqid2taxid ${db}/kraken2/seqid2taxid.map --taxonomy ${db}/kraken2/taxonomy --kraken database.kraken --output databasemers.kraken -k -l  -t" script as well, just at a much later point in step 3 "CONVERTING KMER MAPPINGS INTO READ CLASSIFICATIONS".
