### ISSUE TITLE
NoneType' object has no attribute 'level_num' Braken 2.6

### ISSUE THREAD

**Issue by SilasK** [jenniferlu717/Bracken#126]
Hello I get this error!

```
(bracken) [kiesers@login2 Poppunk]$ bracken -d kraken_db/ -i ERP002061_fastq/ERR210758.report -o ERP002061_fastq/ERR210758.bracken ERP002061_fastq/ERR210758.txt -r 50 -l S
 >> Checking for Valid Options...
 >> Running Bracken
      >> python src/est_abundance.py -i ERP002061_fastq/ERR210758.report -o ERP002061_fastq/ERR210758.bracken -k kraken_db/database100mers.kmer_distrib -l S -t 0
PROGRAM START TIME: 10-23-2020 16:04:39
Traceback (most recent call last):
  File "/home/kiesers/scratch/miniconda3/envs/bracken/bin/src/est_abundance.py", line 488, in <module>
    main()
  File "/home/kiesers/scratch/miniconda3/envs/bracken/bin/src/est_abundance.py", line 241, in main
    while level_num != (prev_node.level_num + 1):
AttributeError: 'NoneType' object has no attribute 'level_num'

```

**Comment by jenniferlu717** [comment]
I would need to see the report file. What database are you using/did you modify the taxonomy? It could be that you're missing a taxon so Bracken is trying to connect to something that isnt there.

**Comment by punnettsun** [comment]
Hi,

I thought I should add in that I had this same exact problem and was able to solve it! I had made my own nodes & names dmp files that are different from NCBI's taxonomy files so if you are also using your own dmp files, then maybe you have the same problem I had. Apparently my nodes and names.dmp files were missing a very much needed column. The nodes.dmp file should have these columns with these delimiters:
"taxid\t|\tdisplay_name\t|\t-\t|\tscientific name\t|\n"

The names.dmp file should have these columns with these delimiters:
"taxid\t|\tparent_taxid\t|\trank\t|\t-\t|\n"

I was missing the column where there are "-" in them. Once I fixed this, I did not have the 'NoneType' attribute error that you also have. Maybe this helps or maybe not. I hope it works out!

Best
Punit

**Comment by SilasK** [comment]
Yes, I use my custom nodes.dmp . This is likely the problem. Thank you for your help.

**Comment by SilasK** [comment]
@punnettsun I assume you inverted nodes and names.dmp isn't it?

**Comment by punnettsun** [comment]
@SilasK I was having a different problem. I had tried using FlexTaxD before as well though! However, because of some bugs that existed before the latest release in the nodes & names dmp file (some nodes would be stranded without a proper parent node & I had to keep adding in the node for Archaea), I ended up making my own nodes.dmp & names.dmp files using my own Python script & I can also add in my strain nodes as well without having to specifically add them using a modification file that FlexTaxD did in an earlier version. My own script has worked well with Kraken & Bracken & also Centrifuge but it only takes into account Bacteria & Archaea as those are the only domains I need for my work.

**Comment by davve2** [comment]
https://github.com/FOI-Bioinformatics/flextaxd/releases/tag/v.0.3.3
https://github.com/FOI-Bioinformatics/flextaxd/issues/25
