### ISSUE TITLE
Bracken "Value Error: not enough values to unpack (expected 3, got 1)

### ISSUE THREAD

**Issue by Virome1** [jenniferlu717/Bracken#161]
Hi, 

I am running bracken and using the following database: https://bridges.monash.edu/projects/Metagenomics_Index_Correction/65534

This is the error I am getting:
`Traceback (most recent call last):
  File "/opt/software/conda_env/bin/src/est_abundance.py", line 488, in <module>
    main()
  File "/opt/software/conda_env/bin/src/est_abundance.py", line 287, in main
    [mapped_taxid, mapped_taxid_dict] = process_kmer_distribution(line,lvl_taxids,map2lvl_taxids)
  File "/opt/software/conda_env/bin/src/est_abundance.py", line 99, in process_kmer_distribution
    [g_taxid,mkmers,tkmers] = genome_str.split(':')
ValueError: not enough values to unpack (expected 3, got 1)
`
Any help would be appreciated

**Comment by ZhangDengwei** [comment]
> I've got the same issue. Anyone wanna share a solution? Many thanks.
> 
> I'm using Krakenuniq with the pre-built database downloaded from https://benlangmead.github.io/aws-indexes/k2, the 384G one EuPathDB48, to generate the report file.

Hi @fengyuchengdu , have you addressed this issue?
