### ISSUE TITLE
The newest version should now work with krakenuniq databases.

### ISSUE THREAD

**Issue by phlatphish** [jenniferlu717/Bracken#203]
The newest version should now work with krakenuniq databases.

_Originally posted by @jenniferlu717 in https://github.com/jenniferlu717/Bracken/issues/197#issuecomment-1275173419_
      
v 2.8 looks like it is still looking for a kraken2 type database, even though I specified krakenuniq with the -y parameter

> /home/xxx/build/Bracken/bracken-build -h
/home/xxx/build/Bracken/bracken-build: illegal option -- h
Usage: bracken_build -k KMER_LEN -l READ_LEN -d MY_DB -x K_INSTALLATION -y K_TYPE -t THREADS
KMER_LEN kmer length used to build the kraken database (default: 35)
THREADS the number of threads to use when running kraken classification and the bracken scripts
READ_LEN read length to get all classifications for (default: 100)
MY_DB location of Kraken database
K_INSTALLATION location of the installed kraken/kraken-build scripts (default assumes scripts can be run from the user path)
K_TYPE version of kraken to use (default = kraken2 - other options: kraken, krakenuniq)

> /home/xxx/build/Bracken/bracken-build -k 35 -l 75 -d /data/xxx/db_052422 -x ~/miniconda3/envs/krakenuniq/bin -y krakenuniq -t 32

Selected Options:
kmer length = 35
read length = 75
database = /data/cjb/db_052422
threads = 32
kraken type = krakenuniq
Checking for Valid Options...
ERROR: Kraken2 Database incomplete: /data/xxx/db_052422/hash.k2d does not exist

**Comment by phlatphish** [comment]
Subsequently, bracken ran cleanly using that database on krakenuniq reports.

**Comment by fengyuchengdu** [comment]
I'm using Krakenuniq with the pre-built database downloaded from https://benlangmead.github.io/aws-indexes/k2, the 384G one labelled as EuPathDB48, to generate the report file.

Bracken was installed by the install shell rather than via conda

when I ran the program, it said

bracken -d ~/krakenuniq -i new_report.tsv -o new_bracken -w new_bracken_report -r 50 -l S -t 0
 >> Checking for Valid Options...
 >> Running Bracken
      >> python src/est_abundance.py -i new_report.tsv -o new_bracken -k /hdd1/home/f22_yfeng/krakenuniq/database50mers.kmer_distrib -l S -t 0
PROGRAM START TIME: 10-13-2022 11:57:37
>> Checking report file: new_report.tsv
Traceback (most recent call last):
  File "/hdd1/home/f22_yfeng/Bracken/src/est_abundance.py", line 554, in <module>
    main()
  File "/hdd1/home/f22_yfeng/Bracken/src/est_abundance.py", line 339, in main
    [mapped_taxid, mapped_taxid_dict] = process_kmer_distribution(line,lvl_taxids,map2lvl_taxids)
  File "/hdd1/home/f22_yfeng/Bracken/src/est_abundance.py", line 100, in process_kmer_distribution
    [g_taxid,mkmers,tkmers] = genome_str.split(':')
ValueError: not enough values to unpack (expected 3, got 1)

I'm wondering how can I fix this ?

Many thanks

**Comment by jenniferlu717** [comment]
@phlatphish Can you try running without the -x flag? 

Otherwise, i did fix the script. I accidentally left kraken2 as the default - ignoring the -y flag - when specifying -x. But the newest version does fix this

**Comment by jenniferlu717** [comment]
@fengyuchengdu can you open a new issue? I think your kmer_distribution file might be wrong. I need to see the kmer_distribution file you downloaded/are you using
