### ISSUE TITLE
`IndexError: string index out of range` for clade Bacteria with empty level

### ISSUE THREAD

**Issue by fluhus** [jenniferlu717/Bracken#284]
Hi,

Thank you for making this tool! :)

I am running Bracken 2.9 on Kraken2's report (small subsample attached below), and I am getting an out of range error. It seems to come from an empty level value for Bacteria.

Command:

```
$ ./bracken -d .../kraken2/standard -i example.txt -o a -r 100
```

Output:

```
 >> Checking for Valid Options...
 >> Running Bracken 
      >> python src/est_abundance.py -i example.txt -o a -k .../kraken2/standard/database100mers.kmer_distrib -l S -t 0
PROGRAM START TIME: 10-20-2024 04:04:30
>> Checking report file: example.txt
Traceback (most recent call last):
  File ".../Bracken-2.9/./src/est_abundance.py", line 557, in <module>
    main()
  File ".../Bracken-2.9/./src/est_abundance.py", line 326, in main
    elif main_lvls.index(level_id[0]) >= branch_lvl:
                         ~~~~~~~~^^^
IndexError: string index out of range
```

I am not sure if this is a bug in Kraken2 or with Bracken. I noticed that Bacteria, Archaea and Viruses all have empty levels.

Regardless, perhaps level_id can be checked for validity before subscripting, allowing for a more informative error message.

Thanks!

[example.txt](https://github.com/user-attachments/files/17448819/example.txt)

**Comment by SMUZhanLi** [comment]
> Hi,
> 
> Thank you for making this tool! :)
> 
> I am running Bracken 2.9 on Kraken2's report (small subsample attached below), and I am getting an out of range error. It seems to come from an empty level value for Bacteria.
> 
> Command:
> 
> ```
> $ ./bracken -d .../kraken2/standard -i example.txt -o a -r 100
> ```
> 
> Output:
> 
> ```
>  >> Checking for Valid Options...
>  >> Running Bracken 
>       >> python src/est_abundance.py -i example.txt -o a -k .../kraken2/standard/database100mers.kmer_distrib -l S -t 0
> PROGRAM START TIME: 10-20-2024 04:04:30
> >> Checking report file: example.txt
> Traceback (most recent call last):
>   File ".../Bracken-2.9/./src/est_abundance.py", line 557, in <module>
>     main()
>   File ".../Bracken-2.9/./src/est_abundance.py", line 326, in main
>     elif main_lvls.index(level_id[0]) >= branch_lvl:
>                          ~~~~~~~~^^^
> IndexError: string index out of range
> ```
> 
> I am not sure if this is a bug in Kraken2 or with Bracken. I noticed that Bacteria, Archaea and Viruses all have empty levels.
> 
> Regardless, perhaps level_id can be checked for validity before subscripting, allowing for a more informative error message.
> 
> Thanks!
> 
> [example.txt](https://github.com/user-attachments/files/17448819/example.txt)

Hi, fluhus. It appears to be a bug caused by using the latest kraken2 dabase (version 2024-09-04), including [Standard](https://genome-idx.s3.amazonaws.com/kraken/k2_standard_20240904.tar.gz), [Standard-16](https://genome-idx.s3.amazonaws.com/kraken/k2_standard_16gb_20240904.tar.gz) and [Standard-8](https://genome-idx.s3.amazonaws.com/kraken/k2_standard_08gb_20240904.tar.gz). Please use an older version database, e.g. version 2024-06-05 (https://genome-idx.s3.amazonaws.com/kraken/k2_standard_20240605.tar.gz).

**Comment by fluhus** [comment]
Thank you, @SMUZhanLi!

I got the DB you linked to and I am still getting empty levels for Bacteria, Archaea and Viruses. I tried with both kraken2 v2.1.3 and with the current master branch.

Here is my kraken command:

```sh
kraken2 --threads 4 --db standard --output - --report $fout --paired $fin1 $fin2
```

If the problem is in Kraken, I guess the relevant issue for Bracken would be to check input validity and stop with an informative error if invalid.

**Comment by fluhus** [comment]
I edited the report file manually and added a 'D' level to Bacteria, Archaea, Viruses and Eukaryotes.

Now I am getting this:

```
 >> Checking for Valid Options...
 >> Running Bracken 
      >> python src/est_abundance.py -i example.txt -o a -k /dfs7/whitesonlab/faracig/databases/kraken_db_standard/database100mers.kmer_distrib -l S -t 0
PROGRAM START TIME: 10-21-2024 22:43:39
>> Checking report file: example.txt
Traceback (most recent call last):
  File "/dfs7/whitesonlab/alavon/Tools/bracken/./src/est_abundance.py", line 563, in <module>
    main()
  File "/dfs7/whitesonlab/alavon/Tools/bracken/./src/est_abundance.py", line 299, in main
    while level_num != (prev_node.level_num + 1):
                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'level_num'
```

**Comment by SMUZhanLi** [comment]
> I edited the report file manually and added a 'D' level to Bacteria, Archaea, Viruses and Eukaryotes.
> 
> Now I am getting this:
> 
> ```
>  >> Checking for Valid Options...
>  >> Running Bracken 
>       >> python src/est_abundance.py -i example.txt -o a -k /dfs7/whitesonlab/faracig/databases/kraken_db_standard/database100mers.kmer_distrib -l S -t 0
> PROGRAM START TIME: 10-21-2024 22:43:39
> >> Checking report file: example.txt
> Traceback (most recent call last):
>   File "/dfs7/whitesonlab/alavon/Tools/bracken/./src/est_abundance.py", line 563, in <module>
>     main()
>   File "/dfs7/whitesonlab/alavon/Tools/bracken/./src/est_abundance.py", line 299, in main
>     while level_num != (prev_node.level_num + 1):
>                         ^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'level_num'
> ```

Hi, fluhus. I noticed  another error that the level of Duplodnaviria is "1" in my kraken2 report, but the true taxonomic level is "D1" in ${kraken2-standard-db}/ktaxonomy.tsv.  So, I edited the py script to fix the wrong taxonomic levels for kraken2 report. 
```shell
check_kraken2_report.py -i kraken2.report -k ${kraken2-standard-db}/ktaxonomy.tsv -o check.kraken2.report
```

[check_kraken2_report.py](https://github.com/SMUZhanLi/CheckKraken2Report)

**Comment by gaferguz** [comment]
@SMUZhanLi! Hi there! I recently encountered one of the reported bugs related to generating kraken2 reports with empty fields when using an EC2 instance running Ubuntu 24.04 LTS. I’ve tested this with different versions of Kraken2 (v2.1.3 and v2.1.1) Bracken (v2.6.1 and v2.9) and even python (3.12.8 and 3.12.3), but the issue persists. Bracken throws the following error:

```
 >> Checking for Valid Options...
 >> Running Bracken 
      >> python src/est_abundance.py -i File.kreport -o File.bracken -k /home/ubuntu/FUTUR25/database100mers.kmer_distrib -l S -t 10
>> Checking report file: File.kreport
PROGRAM START TIME: 01-16-2025 08:30:44
Traceback (most recent call last):
  File "/home/ubuntu/Bracken-2.6.1/src/est_abundance.py", line 529, in <module>
    main()
  File "/home/ubuntu/Bracken-2.6.1/src/est_abundance.py", line 302, in main
    elif main_lvls.index(level_id[0]) >= branch_lvl:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: '1' is not in list
```

I have tried to avoid this by adding those ranks to each kraken2 report myself:

`cat File.kreport | sed "s/\t\t1\t/\tR\t1\t/g" | sed "s/\t\t2\t/\tD\t2\t/g" | sed "s/\t\t2759\t/\tD\t2759\t/g" | sed "s/\t\t2157\t/\tD\t2157\t/g" | sed "s/\t\t10239\t/\tD\t10239\t/g" > File2.kreport `

After that, the code breaks with the same error that is stated in this issue.

```
 >> Checking for Valid Options...
 >> Running Bracken 
      >> python src/est_abundance.py -i File.kreport -o File.bracken -k /home/ubuntu/FUTUR25/database100mers.kmer_distrib -l S -t 0
>> Checking report file: File.kreport
PROGRAM START TIME: 01-17-2025 09:00:08
Traceback (most recent call last):
  File "/home/ubuntu/Bracken-2.9/src/est_abundance.py", line 554, in <module>
    main()
  File "/home/ubuntu/Bracken-2.9/src/est_abundance.py", line 291, in main
    while level_num != (prev_node.level_num + 1):
                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'level_num'
```

Do you have any recommendations for resolving it?
