### ISSUE TITLE
Problems building database

### ISSUE THREAD

**Issue by franciscozorrilla** [jenniferlu717/Bracken#69]
Hello,

I built my KRAKEN2 database as shown below

```
#!/usr/bin/env bash
#SBATCH -A SNIC2018-3-18
#SBATCH -N 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 20
#SBATCH -C MEM64|MEM128
#SBATCH -t 1-00:00:00

kraken2-build --standard --threads 20 --db /c3se/users/zorrilla/Hebbe/projects/KRAKEN2_DB
```

Job output:

```
Downloading nucleotide est accession to taxon map... done.
Downloading nucleotide gb accession to taxon map... done.
Downloading nucleotide gss accession to taxon map... done.
Downloading nucleotide wgs accession to taxon map... done.
Downloaded accession to taxon map(s)
Downloading taxonomy tree data... done.
Uncompressing taxonomy data... done.
Untarring taxonomy tree data... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
All files processed, cleaning up extra sequence files... done, library complete.
Downloading UniVec_Core data from FTP...done.
Adding taxonomy ID of 28384 to all sequences...done.
Masking low-complexity regions of downloaded library... done.
Creating sequence ID to taxonomy ID map (step 1)...
Sequence ID to taxonomy ID map complete. [0.211s]
Estimating required capacity (step 2)...
Estimated hash table requirement: 37086853120 bytes
Capacity estimation complete. [8m59.096s]
Building database files (step 3)...
Taxonomy parsed and converted.
CHT created with 15 bits reserved for taxid.
Completed processing of 43476 sequences, 60059620226 bp
Writing data to disk...  complete.
Database files completed. [54m2.220s]
Database construction complete. [Total: 1h3m1.572s]
```
This resulted in the following files:
![image](https://user-images.githubusercontent.com/35606471/51273486-1c949380-19cd-11e9-94f9-4e50f27e624f.png)

Next I tried to build my BRACKEN library as shown below: 

```
#!/usr/bin/env bash
#SBATCH -A SNIC2018-3-18
#SBATCH -N 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 20
#SBATCH -C MEM64|MEM128
#SBATCH -t 1-00:00:00

bracken-build -d /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/KRAKEN2_DB -t 20 -k 35
```
This results in the following output:

```
 >> Selected Options:
       kmer length = 35
       read length = 100
       database    = /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/KRAKEN2_DB
       threads     = 20
 >> Checking for Valid Options...
 >> Creating database.kraken [if not found]
          database.kraken exists, skipping creation....
          Finished creating database.kraken [in DB folder]
 >> Creating database100mers.kmer_distrib 
	>>STEP 0: PARSING COMMAND LINE ARGUMENTS
		Taxonomy nodes file: /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/KRAKEN2_DB/taxonomy/nodes.dmp
		Seqid file:          /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/KRAKEN2_DB/seqid2taxid.map
		Num Threads:         20
		Kmer Length:         35
		Read Length:         100
	>>STEP 1: READING SEQID2TAXID MAP
		0 sequences read
		1000 sequences read
		2000 sequences read
                      ..........
		43000 sequences read
		43476 total sequences read
	>>STEP 2: READING NODES.DMP FILE
		0 nodes read
		1000 nodes read
		2000 nodes read
                    ..............
		2043000 nodes read
		2044000 nodes read
		2044356 total nodes read
	>>STEP 3: READING DATABASE.KRAKEN FILE
		0 sequences read...
		0 total sequences read
	>>STEP 4: CONVERTING KMER MAPPINGS INTO READ CLASSIFICATIONS:
		100mers, with a database built using 35mers
		0 sequences converted...
		0 sequences converted...
	Time Elaped: 0 minutes, 2 seconds, 0.00000 microseconds
	=============================
PROGRAM START TIME: 01-16-2019 19:14:52
Traceback (most recent call last):
  File "/c3se/users/zorrilla/Hebbe/.conda/envs/checkm_env/bin/generate_kmer_distribution.py", line 161, in <module>
    main()
  File "/c3se/users/zorrilla/Hebbe/.conda/envs/checkm_env/bin/generate_kmer_distribution.py", line 110, in main
    i_file = open(args.input, 'r')
IOError: [Errno 2] No such file or directory: '/c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/KRAKEN2_DB/database100mers.kraken'
```

It seems like BRACKEN is trying to look for database100mers.kraken in my KRAKEN_DB folder, but this folder contains the file database.kraken instead. 

I should mention that I replaced my bracken-build script with the one from pull request #64. Maybe this caused some unforeseen issue?

Also, it looks like steps 3 and 4 are not functioning properly (0 sequences read/converted). 

Any idea what could be going wrong?

Kind regards,
Francisco

**Comment by franciscozorrilla** [comment]
It should be noted that the database.kraken file is empty.
After deleting this file, and rerunning using 


`$ bracken-build -d /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/KRAKEN2_DB -x /c3se/users/zorrilla/Hebbe/.conda/pkgs/kraken2-2.0.7_beta-pl526h2d50403_0/libexec/`

I obtain the following output:
```
 >> Selected Options:
       kmer length = 35
       read length = 100
       database    = /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/KRAKEN2_DB
       threads     = 1
 >> Checking for Valid Options...
 >> Creating database.kraken [if not found]
      >> /c3se/users/zorrilla/Hebbe/.conda/pkgs/kraken2-2.0.7_beta-pl526h2d50403_0/libexec/kraken2 --db /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/KRAKEN2_DB --threads 1 <( find -L /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/KRAKEN2_DB/library \( -name *.fna -o -name *.fa -o -name *.fasta \) -exec cat {} + ) > /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/KRAKEN2_DB/database.kraken
/c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/.conda/pkgs/kraken2-2.0.7_beta-pl526h2d50403_0/libexec/classify: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/.conda/pkgs/kraken2-2.0.7_beta-pl526h2d50403_0/libexec/classify)
```
I will try uninstalling and reinstalling KRAKEN2 but other than that im not sure what to do.
Any suggestions?

**Comment by franciscozorrilla** [comment]
The problem was being caused by the fact that I was pointing -x towards the conda package location:
`/c3se/users/zorrilla/Hebbe/.conda/pkgs/kraken2-2.0.7_beta-pl526h2d50403_0/libexec/`

When I shoudl have been pointing towards the conda environment bin location:
`/c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/.conda/envs/checkm_env/bin/`

Hope this saves someone some pain in the future.

**Comment by franciscozorrilla** [comment]
Seems like it was a memory issue, switching from a 64 to 128 GB RAM node did the trick.

**Comment by s4251484** [comment]
> The problem was being caused by the fact that I was pointing -x towards the conda package location:
> `/c3se/users/zorrilla/Hebbe/.conda/pkgs/kraken2-2.0.7_beta-pl526h2d50403_0/`
>
> When I shoudl have been pointing towards the conda environment bin location:
> `/c3se/NOBACKUP/groups/c3-c3se605-17-8/projects_francisco/.conda/envs/checkm_env/bin/`
> 
> Hope this saves someone some pain in the future.

Hi @franciscozorrilla i guess i encounter the similar issue. i installed bracken via conda, and found a whole bunch of perl folders and zipped files in my .conda/pkgs - are they supposed to be sitting within my bracken conda-env instead? 
my issue now is there is no "bracken" command and i dont find any bracken in my env bracken/bin, but only bracken.json in the conda-meta folder. please help, many thanks!
